version: "3.8"

services:
  agentdbpostgres:
    image: pgvector/pgvector:pg16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER required}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD required}
      POSTGRES_DB: ${POSTGRES_DB:-VectorDB}
    ports:
      - "${PG_PORT:-5442}:5432"
    volumes:
      - VectorDB:/var/lib/postgresql/data

volumes:
  VectorDB:
