# URLs for the Multi-Server MCP Client, which provides external tools.
mcp_clients:
  MCP1:
    url: "https://MCP1.fastmcp.app/mcp"
    transport: "streamable_http"
  MCP2:
    url: "https://MCP3.fastmcp.app/mcp"
    transport: "streamable_http"
  MCP3:
    url: "https://MCP3.fastmcp.app/mcp"
    transport: "streamable_http"
